
stages :
- stage: Dev
  jobs:
  - deployment: Dev
    displayName: web
    pool:
      vmImage: 'Ubuntu-16.04'
    environment:
      name: Dev
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script:  |
                cd /var/www/CUBE
                sudo git pull origin Dev
- stage: QA
  condition: succeeded()
  jobs:
  - deployment: QA
    displayName: web
    pool:
      vmImage: 'Ubuntu-16.04'
    environment:
      name: QA
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script:  |
                cd /var/www/CUBE
                sudo git pull origin Dev
 
- stage: Prod
  
  jobs:
  - deployment: Prod
    displayName: web
    pool:
      vmImage: 'Ubuntu-16.04'
    environment:
      name: Production
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script:  |
                cd /var/www/CUBE
                sudo git pull origin Dev